blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('', views.blog, name='blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
]

carrito/urls.py
from django.urls import path
from . import views

app_name="carrito"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('vaciar/', views.vaciar_carrito, name='vaciar'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoWebApp.urls')),
    path('servicios/', include('Servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carrito/', include('carrito.urls')),
    path('autenticacion/', include('autenticacion.urls'))
]

# Registrar url de imagenes
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from tienda import views

urlpatterns = [
    path('', views.tienda, name='tienda'),
]

carrito/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'categoriaProducto'
        verbose_name_plural = 'categoriasProducto'

class Producto(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField()
    stock = models.BooleanField(default=True)
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    categorias = models.ForeignKey(CategoriaProducto, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'

carrito/views.py
from django.shortcuts import redirect
from .carrito import Carrito
from tienda.models import Producto
from django.http import JsonResponse
import json

# Create your views here.

def agregar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.agregarProducto(producto)
    return redirect("tienda")
    print(carrito)
    carrito1 = json.dumps(carrito.carrito)
    print(carrito1)
    return JsonResponse(carrito1)

def eliminar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.eliminarProducto(producto)
    return redirect("tienda")

def restar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.restarProducto(producto)
    return redirect("tienda")

def vaciar_carrito(request):
    carrito = Carrito(request)
    carrito.vaciarCarrito()
    return redirect("tienda")

tienda/views.py
from django.shortcuts import render
from .models import Producto
# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    return render(request, 'tienda/tienda.html', {'productos': productos})

tienda/templates/carrito/widget.html
<div class="d-grid gap-2 d-md-flex justify-content-end sticky-top pt-2">
    <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight"
        aria-controls="offcanvasRight">Ver carrito <i class="fa-solid fa-cart-shopping"></i></button>
</div>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel" style="--bs-offcanvas-width: 500px">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasRightLabel">Carrito de compras <i
                class="fa-solid fa-cart-shopping"></i></h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">

        <table class="table align-middle">
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Suma</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% if request.session.carrito.items %}
                {% for key, value in request.session.carrito.items %}
                <tr>
                    <td>{{ value.nombre }}</td>
                    <td>
                        <a href="{% url 'carrito:agregar' value.id %}" class="btn btn-sm btn-success" style="width: 27px;">+</a>
                        <span class="mx-2">{{ value.cantidad }}</span>
                        <a href="{% url 'carrito:restar' value.id %}" class="btn btn-sm btn-danger" style="width: 27px;">-</a>
                    </td>
                    <td>
                        ${{ value.precio }}
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">
                        <div class="alert alert-danger text-center">
                            Sin productos
                        </div>
                    </td>
                </tr>
                {% endif %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        Total: ${{ importe_total_carrito }}
                    </td>
                </tr>
            </tfoot>
        </table>

    </div>
</div>